name: Build README

on:
  push:
  workflow_dispatch:
  schedule:
    - cron: '30 20 * * *'

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
    - name: Checkout repo
      uses: actions/checkout@v2
    - name: Download babashka
      run: |
        curl -sLO https://github.com/babashka/babashka/releases/download/v1.1.173/babashka-1.1.173-linux-amd64-static.tar.gz
        tar xf babashka-1.1.173-linux-amd64-static.tar.gz
    - name: render
      run: |
        ./bb render.clj > README.md
        cat README.md
    - name: commit and push if changed
      run: |
        test -z "$(git status --porcelain -uno)" && exit 0
        git diff
        git config --global user.email "readme-bot@example.com"
        git config --global user.name "README-bot"
        git commit -am "Updated content"
        git push
